future: false
markdown: kramdown
permalink: ":categories/:title.html"
timezone: Europe/London
gems:
  - jekyll-feed
title: Peter Hilton’s blog
author: Peter Hilton
description: Programming and other curiosities